### ISSUE TITLE
Crashing on opening server PreviewMessageLinks.plugin.js

### ISSUE THREAD

**Issue by keatit71** [dylan-dang/BetterDiscordPlugins#6]
Plugin causes my discord to crash when trying to open a server after attempting to preview a message with preview message links v0.0.1. 

HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 
Component stack:
     at MessageEmbedError (betterdiscord://plugins/PreviewMessageLinks.plugin.js:271:5)
    at betterdiscord://plugins/PreviewMessageLinks.plugin.js:217:30
    at t (https://discord.com/assets/75c33c6cdfb1b86a6711.js:601:544)
    at ConnectedMessageAccessories
    at div
    at t.default (https://discord.com/assets/a78064493ce8bd65d361.js:2195:9)
    at li
    at t.default (https://discord.com/assets/a78064493ce8bd65d361.js:2195:9)
    at https://discord.com/assets/e33b89d5662219957b39.js:1154:540
    at ol
    at div
    at T (https://discord.com/assets/a78064493ce8bd65d361.js:2206:293)
    at div
    at https://discord.com/assets/e33b89d5662219957b39.js:1808:624
    at div
    at h (https://discord.com/assets/a78064493ce8bd65d361.js:4083:696)
    at W (https://discord.com/assets/e33b89d5662219957b39.js:1201:11)
    at main
    at Ue (https://discord.com/assets/7048c4bf3dd822f2ead5.js:82:861)
    at https://discord.com/assets/e33b89d5662219957b39.js:1820:543
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:3669:407)
    at ChatLayerProvider
    at t (https://discord.com/assets/95c2aff9208d35fa6c2d.js:32:907)
    at t (https://discord.com/assets/7048c4bf3dd822f2ead5.js:91:677)
    at https://discord.com/assets/7048c4bf3dd822f2ead5.js:97:172
    at div
    at div
    at t (https://discord.com/assets/7048c4bf3dd822f2ead5.js:60:272)
    at e (https://discord.com/assets/b7d3144ef99598fcac78.js:50:233)
    at https://discord.com/assets/95c2aff9208d35fa6c2d.js:71:936
    at https://discord.com/assets/7048c4bf3dd822f2ead5.js:74:282
    at ve (https://discord.com/assets/7048c4bf3dd822f2ead5.js:40:779)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6122:926)
    at c (https://discord.com/assets/a78064493ce8bd65d361.js:2025:11)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6125:10)
    at div
    at div
    at div
    at t.default (https://discord.com/assets/7048c4bf3dd822f2ead5.js:34:22)
    at div
    at l (https://discord.com/assets/a78064493ce8bd65d361.js:4723:10)
    at t (https://discord.com/assets/7048c4bf3dd822f2ead5.js:142:915)
    at div
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:4624:564)
    at t (https://discord.com/assets/7048c4bf3dd822f2ead5.js:145:505)
    at Y (https://discord.com/assets/7048c4bf3dd822f2ead5.js:147:69)
    at div
    at t (https://discord.com/assets/7048c4bf3dd822f2ead5.js:306:360)
    at j (https://discord.com/assets/7048c4bf3dd822f2ead5.js:125:188)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6122:926)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6125:10)
    at t (https://discord.com/assets/7048c4bf3dd822f2ead5.js:227:369)
    at Suspense
    at d
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6122:926)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6125:10)
    at div
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:3669:407)
    at VerificationLayerProvider
    at E (https://discord.com/assets/a78064493ce8bd65d361.js:2514:293)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:3669:407)
    at AppLayerProvider
    at div
    at div
    at E (https://discord.com/assets/a78064493ce8bd65d361.js:1949:255)
    at T (https://discord.com/assets/a78064493ce8bd65d361.js:2206:293)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:746:655)
    at m (https://discord.com/assets/a78064493ce8bd65d361.js:750:113)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:750:584)
    at u (https://discord.com/assets/a78064493ce8bd65d361.js:4279:598)
    at h (https://discord.com/assets/a78064493ce8bd65d361.js:730:572)
    at re (https://discord.com/assets/a78064493ce8bd65d361.js:734:313)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:791:116)
    at u (https://discord.com/assets/a78064493ce8bd65d361.js:4278:528)
    at https://discord.com/assets/a78064493ce8bd65d361.js:4788:30
    at H (https://discord.com/assets/a78064493ce8bd65d361.js:5936:700)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6119:570)
    at t (https://discord.com/assets/a78064493ce8bd65d361.js:6075:817)
    at _ (https://discord.com/assets/a78064493ce8bd65d361.js:2561:813)

**Comment by maenDisease** [comment]
The crashing is due to message links being loaded. Try pull request #7
